const MARKETS = [
  { id: "sita-morning",      slug: "SITA%20MORNING",       name: "SITA MORNING",      open: "09:45", close: "10:45", result: "10:45", days: "All days", live: true },
  { id: "star-tara-morning", slug: "STAR%20TARA%20MORNING", name: "STAR TARA MORNING", open: "10:10", close: "11:10", result: "11:10", days: "All days", live: true },
  { id: "milan-morning",     slug: "MILAN%20MORNING",       name: "MILAN MORNING",     open: "10:30", close: "11:30", result: "11:30", days: "All days", live: true },
  { id: "andhra-morning",    slug: "ANDHRA%20MORNING",      name: "ANDHRA MORNING",    open: "10:40", close: "11:40", result: "11:40", days: "All days", live: true },
  { id: "madhur-morning",    slug: "MADHUR%20MORNING",      name: "MADHUR MORNING",    open: "11:30", close: "12:30", result: "12:30", days: "All days", live: true },
  { id: "sridevi",           slug: "SRIDEVI",               name: "SRIDEVI",           open: "11:35", close: "12:35", result: "12:35", days: "All days", live: true },
  { id: "kalyan-morning",    slug: "Kalyan%20Morning",      name: "Kalyan Morning",    open: "11:40", close: "12:40", result: "12:40", days: "All days", live: true },
  { id: "kamal-morning",     slug: "KAMAL%20MORNING",       name: "KAMAL MORNING",     open: "12:10", close: "13:10", result: "13:10", days: "All days", live: true },
  { id: "time-bazar",        slug: "TIME%20BAZAR",          name: "TIME BAZAR",        open: "13:00", close: "14:00", result: "14:00", days: "All days", live: true },
  { id: "madhur-day",        slug: "MADHUR%20DAY",          name: "MADHUR DAY",        open: "13:30", close: "14:30", result: "14:30", days: "All days", live: true },
  { id: "sita-day",          slug: "SITA%20DAY",            name: "SITA DAY",          open: "13:45", close: "14:45", result: "14:45", days: "All days", live: true },
  { id: "star-tara-day",     slug: "STAR%20TARA%20DAY",     name: "STAR TARA DAY",     open: "14:20", close: "15:20", result: "15:20", days: "All days", live: true },
  { id: "milan-day",         slug: "MILAN%20DAY",           name: "MILAN DAY",         open: "15:00", close: "17:00", result: "17:00", days: "All days", live: true },
  { id: "rajdhani-day",      slug: "RAJDHANI%20DAY",        name: "RAJDHANI DAY",      open: "15:10", close: "17:10", result: "17:10", days: "All days", live: true },
  { id: "supreme-day",       slug: "SUPREME%20DAY",         name: "SUPREME DAY",       open: "15:35", close: "17:35", result: "17:35", days: "All days", live: true },
  { id: "andhra-day",        slug: "ANDHRA%20DAY",          name: "ANDHRA DAY",        open: "15:35", close: "17:35", result: "17:35", days: "All days", live: true },
  { id: "kamal-day",         slug: "KAMAL%20DAY",           name: "KAMAL DAY",         open: "15:40", close: "17:40", result: "17:40", days: "All days", live: true },
  { id: "kalyan-main",       slug: "KALYAN",                name: "KALYAN",            open: "16:00", close: "18:00", result: "18:00", days: "All days", live: true },
  { id: "mahadevi",          slug: "MAHADEVI",              name: "MAHADEVI",          open: "16:30", close: "18:30", result: "18:30", days: "All days", live: true },
  { id: "sita-night",        slug: "SITA%20NIGHT",          name: "SITA NIGHT",        open: "18:45", close: "19:45", result: "19:45", days: "All days", live: true },
  { id: "sridevi-night",     slug: "SRIDEVI%20NIGHT",       name: "SRIDEVI NIGHT",     open: "19:15", close: "20:15", result: "20:15", days: "All days", live: true },
  { id: "star-tara-night",   slug: "STAR%20TARA%20NIGHT",   name: "STAR TARA NIGHT",   open: "19:20", close: "20:20", result: "20:20", days: "All days", live: true },
  { id: "kamal-night",       slug: "KAMAL%20NIGHT",         name: "KAMAL NIGHT",       open: "20:45", close: "22:45", result: "22:45", days: "All days", live: true },
  { id: "andhra-night",      slug: "ANDHRA%20NIGHT",        name: "ANDHRA NIGHT",      open: "20:45", close: "22:45", result: "22:45", days: "All days", live: true },
  { id: "supreme-night",     slug: "SUPREME%20NIGHT",       name: "SUPREME NIGHT",     open: "20:45", close: "22:45", result: "22:45", days: "All days", live: true },
  { id: "milan-night",       slug: "MILAN%20NIGHT",         name: "MILAN NIGHT",       open: "21:10", close: "23:10", result: "23:10", days: "All days", live: true },
  { id: "rajdhani-night",    slug: "RAJDHANI%20NIGHT",      name: "RAJDHANI NIGHT",    open: "21:35", close: "23:45", result: "23:45", days: "All days", live: true },
  { id: "kalyan-night",      slug: "KALYAN%20NIGHT",        name: "KALYAN NIGHT",      open: "21:40", close: "23:40", result: "23:40", days: "All days", live: true },
  { id: "main-bazar",        slug: "MAIN%20BAZAR",          name: "MAIN BAZAR",        open: "22:00", close: "24:10", result: "24:10", days: "All days", live: true }
];